### ISSUE TITLE
link to writeup/blog in README.md leads to a HTTP 404 status code

### ISSUE THREAD

**Issue by mylesbartlett72** [MercuryWorkshop/fakemurk#1]
(also, this project looks amazing!  keep up the chromeos hacking!)

**Comment by Scaratek** [comment]
the post on CE's website has not been made yet

**Comment by TheMemeSniper** [comment]
not a fakemurk issue

**Comment by mylesbartlett72** [comment]
> the post on CE's website has not been made yet

Well, I certainly can't wait for it!  The chromeos hacking series has been super interesting!

**Comment by mylesbartlett72** [comment]
the link is also incorrect, the correct one is https://coolelectronics.me/blog/breaking-cros-3

**Comment by mylesbartlett72** [comment]
(although its still a WIP)

**Comment by mylesbartlett72** [comment]
> writeup has been written up

I saw the other day, it was an enjoyable read!
