### ISSUE TITLE
autoupdate.sh sends telemetry even if opted out?

### ISSUE THREAD

**Issue by yccb** [MercuryWorkshop/fakemurk#11]
- [y] I am not reporting an issue unrelated to the fakemurk utilities.
- [y] I am not reporting an issue related to a borked system.
- [y] I am not an angry sysadmin.
- [n] I have attached the complete and full output from the terminal

# ISSUE DESCRIPTION
autoupdate.sh sends telemetry if the file `/mnt/stateful_partition/telemetry_selected` exists. this file is created after ANY telemetry option is chosen, not just accept

# TERMINAL OUTPUT (if any)
n/a

# ADDITIONAL NOTES
it should probably check for `/mnt/stateful_partition/telemetry_opted_in` instead? it looks like that file gets created only if the user accepts telemetry (in mush.sh). the telemetry_selected file just seems to indicate an option has been selected at all

**Comment by CoolElectronics** [comment]
uh oops that's not good
