### ISSUE TITLE
A FakeMurk'd chromebook will still phone home to Google Admin about switching into dev mode

### ISSUE THREAD

**Issue by AstralPhnx** [MercuryWorkshop/fakemurk#12]
- [Y] I am not reporting an issue unrelated to the fakemurk utilities.
- [Y] I am not reporting an issue related to a borked system.
- [Y] I am not an angry sysadmin.
- [N] I have attached the complete and full output from the terminal

# ISSUE DESCRIPTION
When using fakemurk, google admin console WILL report that the device had been switched out of verified mode and into dev mode even if the device is dev mode disabled in admin console. For obvious reasons this is a gigantic red flag and would almost instantly alert a sysadmin that somebody is using fakemurk. See screenshot below for what is seen in the admin console.

![Screenshot 2023-03-15 at 10 03 45 PM](https://user-images.githubusercontent.com/10949323/225259894-eefa314d-7418-484e-aed3-247db35d896b.png)

I am currently still unsure as to what behavior is exactly tripping this issue, it might be the process you go through if you happen to press Ctrl+D right after installing fakemurk however further testing will be required. Will update as I go

# TERMINAL OUTPUT (if any)

# ADDITIONAL NOTES

**Comment by r58Playz** [comment]
Confirmed fixed with terraOS's chromeOS boot images.

**Comment by CoolElectronics** [comment]
https://github.com/r58Playz/terraos
