### ISSUE TITLE
readme typo?‮

### ISSUE THREAD

**Issue by RuralAnemone** [MercuryWorkshop/fakemurk#15]
- [x] I am not reporting an issue unrelated to the fakemurk utilities.
- [x] I am not reporting an issue related to a borked system.
- [x] I am not an angry sysadmin.
- [x] I have attached the complete and full output from the terminal

# ISSUE DESCRIPTION
typo? in readme
# TERMINAL OUTPUT (if any)
https://github.com/MercuryWorkshop/fakemurk#:~:text=or%20105%20image%2C-,then,-(note%20that%20if
# ADDITIONAL NOTES
I'm assuming you could just re-install the v105 or v107 image and try again but I'm not entirely sure what was intended to be here (if anything)
and I might just be missing a joke; if so please pay this no mind :)

**Comment by CoolElectronics** [comment]
... where's the typo, you don't say what it actually is the link just brings me back to the repository

**Comment by CoolElectronics** [comment]
ah never mind, firefox doesn't seem to want to follow the link section for some reason. yeah, i forgot to fill that out
