### ISSUE TITLE
Pollen

### ISSUE THREAD

**Issue by Morcovka** [MercuryWorkshop/fakemurk#19]
- [] I am not reporting an issue unrelated to the fakemurk utilities.
- [] I am not reporting an issue related to a borked system.
- [] I am not an angry sysadmin.
- [] I have attached the complete and full output from the terminal

# ISSUE DESCRIPTION
When trying to edit Pollen in fakemurk, I can't because it's readonly despite doing ":wq!"
# TERMINAL OUTPUT (if any)
        "ExtensionAllowedTypes": null,
        "ExtensionInstallAllowlist": null,
        "ExtensionInstallBlocklist": null,
        "ExtensionSettings": null,
        "PinnedLauncherApps": null,
        "BookmarkBarEnabled": null,
        "LidCloseAction": null,
        "ChromeOsLockOnIdleSuspend": null,
        "PowerManagementIdleSettings": null,
        "ShowFullUrlsInAddressBar": null,
        "HomepageIsNewTabPage": null,
        "HomepageLocation": null,
        "ShowHomeButton": null,
        "EnableSyncConsent": null,
        "PaymentMethodQueryEnabled": null,
        "SafeSitesFilterBehavior": null,
        "SafeBrowsingProtectionLevel": null,
        "ProxySettings": null,
        "DefaultClipboardSetting": null,
        "DefaultImagesSetting": null,
        "DefaultInsecureContentSetting": null,
        "DefaultJavaScriptSetting": null,
        "DefaultJavaScriptJitSetting": null,
        "DefaultNotificationsSetting": null,
        "DefaultPopupsSetting": null,
        "RestoreOnStartup": null,
        "RestoreOnStartupURLs": null,
        "DefaultDownloadDirectory": null,
        "DownloadDirectory": null,
        "DownloadBubbleEnabled": null,
        "OsColorMode": null,
        "ArcPolicy": null
        "SearchSuggestEnabled": false
}
~                                                                                                                                         
"/etc/opt/chrome/policies/managed/policy.json"
"/etc/opt/chrome/policies/managed/policy.json" E212: Can't open file for writing
Press ENTER or type command to continue
# ADDITIONAL NOTES
I tried to use the command "cp" to copy the file policy.json from downloads to the destination but failed to do so.
I also tried to do chmod 777 /etc/opt/chrome/policies/managed/policy.json but it didn't work.

**Comment by CoolElectronics** [comment]
disk failure

do a full recovery and try again
