### ISSUE TITLE
Is it possible to enable android?

### ISSUE THREAD

**Issue by ant-7802** [MercuryWorkshop/fakemurk#20]
Can i enable android app installation? my chromebook by default has it disabled you cant turn it on

**Comment by RuralAnemone** [comment]
yes, it's explained [in the `How it works` section of the readme](https://github.com/mercuryWorkshop/fakemurk/#:~:text=Install%20any%20APK%20on%20the%20google%20play%20store%20(the%20play%20store%20might%20appear%20blank%2C%20in%20which%20case%20you%20should%20download%20the%20aurora%20store%20apk%20and%20install%20it%20with%20the%20package%20installer%20by%20right%20clicking%20on%20the%20file)) that you can either get lucky and have the play store work for you or just use Aurora Store.
