### ISSUE TITLE
Can’t reinstall fakemurk after powerwash due to emergency re-enroll not working

### ISSUE THREAD

**Issue by CloudySensei** [MercuryWorkshop/fakemurk#21]
- [X] I am not reporting an issue unrelated to the fakemurk utilities.
- [X] I am not reporting an issue related to a borked system.
- [X] I am not an angry sysadmin.
- [X] I have attached the complete and full output from the terminal

# ISSUE DESCRIPTION
Trying to reinstall fakemurk after power washing but get a terminal output error
# TERMINAL OUTPUT (if any)
mkdir: cannot create directory ‘/tmp/rootmnt’: File exists
“echo “- - - - - stage 2: patching target rootfs - - - - -“” command failed with exit code 1. 
# ADDITIONAL NOTES
This probably was the result of me power washing. I power washed because the emergency re-enroll didn’t work, and i really desperately needed to re-enroll at the time and it would not work because of something along the lines of the file system being read only.

**Comment by CoolElectronics** [comment]
recover, you're supposed to do that before installing anyway. the actual issue here (if there is one) is revert failing. i would like more details on that

**Comment by CoolElectronics** [comment]
will be fixed by #27 after the merge
