### ISSUE TITLE
after i put in the commands in on the github and rebooted i keep on trying to press control+d but whenever i do it just takes me back to the OS verification is OFF screen, what should i do?

### ISSUE THREAD

**Issue by Juelz512** [MercuryWorkshop/fakemurk#22]
- [] I am not reporting an issue unrelated to the fakemurk utilities.
- [] I am not reporting an issue related to a borked system.
- [] I am not an angry sysadmin.
- [] I have attached the complete and full output from the terminal

# ISSUE DESCRIPTION

# TERMINAL OUTPUT (if any)

# ADDITIONAL NOTES

**Comment by CoolElectronics** [comment]
recover, do it again

**Comment by Juelz512** [comment]
didnt work
