### ISSUE TITLE
Can't Install apk's

### ISSUE THREAD

**Issue by person1593** [MercuryWorkshop/fakemurk#24]
- [x] I am not reporting an issue unrelated to the fakemurk utilities.
- [x] I am not reporting an issue related to a borked system.
- [x] I am not an angry sysadmin.
- [] I have attached the complete and full output from the terminal

# ISSUE DESCRIPTION
Can install anything from the app store because nothing is there. I try to install the aurora apk and it says I need developer mode turned on for the apk to be installed. Any fix for this
# TERMINAL OUTPUT (if any)
N/A
# ADDITIONAL NOTES

**Comment by TheSpiritOfDark** [comment]
open mush root shell, then run android-root.

**Comment by person1593** [comment]
How to you run android-root. All I get is bash: android-root: command not found

**Comment by kxtzownsu** [comment]
Hmmm, the only command is android-sh, there is no android-root, but android-sh puts you in an ADB shell as root so you could find a way to install an APK in there. (pm install "apk path" doesnt work)

**Comment by rainestorme** [comment]
There's a tool that changes the internals of crossystem.sh to allow this, called [FakeAPK](https://github.com/clockworkindustries/FakeAPK). It really is much larger than it needs to be, though - you can run the commands below in a root shell to accomplish everything neccecary:

```sh
sed -i "s/\(cros_debug=\).*/\11/" /usr/bin/crossystem
reboot
```

And to set it back to normal:

```sh
sed -i "s/\(cros_debug=\).*/\10/" /usr/bin/crossystem
reboot
```

Edit: Yes, this will most likely trip something in GAC. I personally don't recommend doing this unless your sysadmin is really, really incompetent.

**Comment by DamienB325** [comment]
I checked if this trips the admin console, with a test device and workspace free trial, and it doesn't seem to show up as in developer mode, still says boot mode is Verified.
<img width="1116" alt="Screen Shot 2023-05-22 at 5 15 13 PM" src="https://github.com/MercuryWorkshop/fakemurk/assets/49534369/13bc362c-6ab1-44a2-9bb6-e67688fab2e5">
