### ISSUE TITLE
Extensions won't download

### ISSUE THREAD

**Issue by johnenderman** [MercuryWorkshop/fakemurk#25]
- [] I am not reporting an issue unrelated to the fakemurk utilities.
- [] I am not reporting an issue related to a borked system.
- [] I am not an angry sysadmin.
- [] I have attached the complete and full output from the terminal

# ISSUE DESCRIPTION
so whenever I try to download any extension, it gives me and error. (See the image below) everything else works just fine so I don't know what the issue is.
# TERMINAL OUTPUT (if any)
n/a (it was normal)
# ADDITIONAL NOTES
here is what happens when I press add to chrome: 
![image](https://user-images.githubusercontent.com/119866089/229583088-7c2c8e0a-168c-44fe-a73d-cfdf0cb50e22.png)

**Comment by Vxlpix** [comment]
You appeared to have hard disabled extensions.

**Comment by johnenderman** [comment]
Oh, Its working now, thank you. I don't remember hard disabling any, lol
