### ISSUE TITLE
Loop "Chromebook will reboot in verified mode" after emergency revert

### ISSUE THREAD

**Issue by botmaker69** [MercuryWorkshop/fakemurk#34]
After an emergency revert, with some policies I assume block devmode entirely, i suddenly cannot remove dev mode or boot. I try to press space or ctrl d and it brings me to a screen stating "Your organization does not allow dev mode. Your device will reboot into verified mode", reboots, and repeats

**Comment by botmaker69** [comment]
> yeah this happened to me when I tried to disable dev mode from the boot screen. try recovering and re-fakemurking

Recovery ain't work, just says the same thing after recovering

**Comment by CoolElectronics** [comment]
weird. i think `unfuck_stateful` is failing somewhere

**Comment by botmaker69** [comment]
Wiping GBB flags was the only thing that fixes it, seems to be blocking "TONORM" apparently
