### ISSUE TITLE
Fakemurked but still unenrolled

### ISSUE THREAD

**Issue by person1593** [MercuryWorkshop/fakemurk#35]
- [] I am not reporting an issue unrelated to the fakemurk utilities.
- [x] I am not reporting an issue related to a borked system.
- [x] I am not an angry sysadmin.
- [] I have attached the complete and full output from the terminal

# ISSUE DESCRIPTION
Fakemurk installed normally, no errors and it rebooted, after connecting to wifi and doing all the steps, when I get to enterprise enrollment, there is none and it is just like I sh1mmered the Chromebook. The fakemurk utilities such as mush still install and can use.
# TERMINAL OUTPUT (if any)
N/A
# ADDITIONAL NOTES
I have recovered and done it again and got the same result. Not sure if it is the specific Chromebook. I am on v105.

**Comment by botmaker69** [comment]
How did you unenroll exactly? Normal check_enrollment=0?

**Comment by person1593** [comment]
Yes

**Comment by Xman10110** [comment]
I'm having this issue too

**Comment by Xman10110** [comment]
Update: This issue does not happen if you use a version 105 recovery image rather than a 107 one.

**Comment by thonkinator** [comment]
You can just click the little "Enterprise Enrollment" button in the lower left corner when it asks if you're setting up the chromebook for you or a child

**Comment by RuralAnemone** [comment]
> You can just click the little "Enterprise Enrollment" button in the lower left corner when it asks if you're setting up the chromebook for you or a child

good point, but a lot of districts are now requiring administrators to enroll chromebooks i.e. you can't enroll with a student account

(afaik)

**Comment by botmaker69** [comment]
goofy test of confidence, are you willing to let it use your computer to
enroll even tho they likely wouldn't see fakemurk

like hell I give it my computer every day bc they ask for it n they ain't
notice it
