### ISSUE TITLE
Manual Enrollment

### ISSUE THREAD

**Issue by scarlettekk** [MercuryWorkshop/fakemurk#36]
- [Y] I am not reporting an issue unrelated to the fakemurk utilities.
- [Y] I am not reporting an issue related to a borked system.
- [Y] I am not an angry sysadmin.
- [N] I have attached the complete and full output from the terminal

# ISSUE DESCRIPTION
Not quite an issue, exactly. More of a question/observation. I installed fakemurk and got the enrollment loop, however at the certificate error screen I just pressed enroll manually, entered my school credentials.... and it worked? It seems like it just fixed itself, but I wanted to check if this actually bypassing the bug, or if I'm going to have the school's IT department breathing down my neck on Monday. ChromeOS 112, if it matters. I initially did a full setup with a 107 recovery, but for some reason it stopped booting after a bit, so I figured I'd try with the latest chromeos.
# TERMINAL OUTPUT (if any)

# ADDITIONAL NOTES
Octopus (Phaser360S)

**Comment by CoolElectronics** [comment]
yeah this works and is easier in a lot of cases. i didn't  mention it in the readme because depending on the enterprise settings the button will be disabled, and i don't want to confuse people
