### ISSUE TITLE
Bootloop after using fakemurk

### ISSUE THREAD

**Issue by 02tz** [MercuryWorkshop/fakemurk#39]
- [N] I am not reporting an issue unrelated to the fakemurk utilities.
- []N I am not reporting an issue related to a borked system.
- [N] I am not an angry sysadmin.
- [N] I have attached the complete and full output from the terminal

# ISSUE DESCRIPTION

Bootloop after using fakemurk

# TERMINAL OUTPUT (if any)

# ADDITIONAL NOTES

After using the script from fakemurk, I press enter to reboot and CTRL D on the dev mode warning screen. It reboots to the same screen and it keeps looping until I press space in which the system is bricked until recovery. I am using version 108 of chrome

**Comment by Xman10110** [comment]
Use either 107 or 105, 108 isn't well supported

**Comment by CoolElectronics** [comment]
closing since stale, and not enough information to work out what this even means

**Comment by 02tz** [comment]
> closing since stale, and not enough information to work out what this even means

What are you talking about 
I said after using fakemurk chromeos is corrupted "ChromeOS is missing or damaged"
fixed it tho

**Comment by 02tz** [comment]
just downgrade to 105
