### ISSUE TITLE
"exit code 1"

### ISSUE THREAD

**Issue by TransculentCheese234** [MercuryWorkshop/fakemurk#4]
- [] I am not reporting an issue unrelated to the fakemurk utilities.
- [] I am not reporting an issue related to a borked system.
- [] I am not an angry sysadmin.

# ISSUE DESCRIPTION
I start fakemurk up and say yes for the option to quickly revert and enroll fast.
# TERMINAL OUTPUT (if any)
"command failed with exit code 1."
# ADDITIONAL NOTES

**Comment by CoolElectronics** [comment]
... logs please

**Comment by MythicalTrashcan** [comment]
> ... logs please

Here is what the logs most likely look like: 



 ________ ________  ___  __    _______   _____ ______   ___  ___  ________  ___  __
|\  _____\\   __  \|\  \|\  \ |\  ___ \ |\   _ \  _   \|\  \|\  \|\   __  \|\  \|\  \
\ \  \__/\ \  \|\  \ \  \/  /|\ \   __/|\ \  \\\__\ \  \ \  \\\  \ \  \|\  \ \  \/  /|_
 \ \   __\\ \   __  \ \   ___  \ \  \_|/_\ \  \\|__| \  \ \  \\\  \ \   _  _\ \   ___  \
  \ \  \_| \ \  \ \  \ \  \\ \  \ \  \_|\ \ \  \    \ \  \ \  \\\  \ \  \\  \\ \  \\ \  \
   \ \__\   \ \__\ \__\ \__\\ \__\ \_______\ \__\    \ \__\ \_______\ \__\\ _\\ \__\\ \__\
    \|__|    \|__|\|__|\|__| \|__|\|_______|\|__|     \|__|\|_______|\|__|\|__|\|__| \|__|

THIS IS FREE SOFTWARE! if you paid for this, you have been scammed and should demand your money back

fakemurk - a tool made by Mercury Workshop to spoof verified boot while enrolled
you can find this script, its explanation, and documentation here: https://github.com/MercuryWorkshop/fakemurk

WARNING: THIS SCRIPT WILL REQUIRE THE REMOVAL OF ROOTFS VERIFICATION, AND THE DISABLING OF AUTOUPDATES
THIS MEANS THAT IF YOU EVER TURN OFF DEVMODE, YOUR SYSTEM WILL BE BRICKED UNTIL RECOVERY

WE ARE NOT RESPONSIBLE FOR DAMAGE, YOU BEING STUPID AND MISUSING THIS, OR GETTING IN TROUBLE
DO YOU UNDERSTAND??

(enter to proceed, ctrl+c to quit)


Would you like to enable rootfs restore? It will add an option to quickly revert all changes and re-enroll. (Y/n)y
----- stage 1: grabbing disk configuration -----
target kern is 2@/dev/mmcblk0p2
target root is 3@/dev/mmcblk0p3

backup kern is 4@/dev/mmcblk0p4
backup root is 5@/dev/mmcblk0p5
----- stage 2: patching target rootfs -----
mkdir: cannot create directory '/tmp/rootmnt': File exists
"echo "----- stage 2: patching target rootfs -----"" command failed with exit code 1. THIS IS A BUG, REPORT IT HERE https://github.com/MercuryWorkshop/fakemurk
localhost /home/chronos/user #

**Comment by CoolElectronics** [comment]
you have to reboot before running it again, those logs are useless

**Comment by MythicalTrashcan** [comment]
Ok. I thought it was some problem that could be fixed that easily.

**Comment by MythicalTrashcan** [comment]
I got error code 6 now. It has the same logs as the other issue.

**Comment by CoolElectronics** [comment]
can you paste the commands i described in #6 and give me the output

**Comment by MythicalTrashcan** [comment]
________ ________  ___  __    _______   _____ ______   ___  ___  ________  ___  __
|\  _____\\   __  \|\  \|\  \ |\  ___ \ |\   _ \  _   \|\  \|\  \|\   __  \|\  \|\  \
\ \  \__/\ \  \|\  \ \  \/  /|\ \   __/|\ \  \\\__\ \  \ \  \\\  \ \  \|\  \ \  \/  /|_
 \ \   __\\ \   __  \ \   ___  \ \  \_|/_\ \  \\|__| \  \ \  \\\  \ \   _  _\ \   ___  \
  \ \  \_| \ \  \ \  \ \  \\ \  \ \  \_|\ \ \  \    \ \  \ \  \\\  \ \  \\  \\ \  \\ \  \
   \ \__\   \ \__\ \__\ \__\\ \__\ \_______\ \__\    \ \__\ \_______\ \__\\ _\\ \__\\ \__\
    \|__|    \|__|\|__|\|__| \|__|\|_______|\|__|     \|__|\|_______|\|__|\|__|\|__| \|__|

THIS IS FREE SOFTWARE! if you paid for this, you have been scammed and should demand your money back

fakemurk - a tool made by Mercury Workshop to spoof verified boot while enrolled
you can find this script, its explanation, and documentation here: https://github.com/MercuryWorkshop/fakemurk

WARNING: THIS SCRIPT WILL REQUIRE THE REMOVAL OF ROOTFS VERIFICATION, AND THE DISABLING OF AUTOUPDATES
THIS MEANS THAT IF YOU EVER TURN OFF DEVMODE, YOUR SYSTEM WILL BE BRICKED UNTIL RECOVERY

WE ARE NOT RESPONSIBLE FOR DAMAGE, YOU BEING STUPID AND MISUSING THIS, OR GETTING IN TROUBLE
DO YOU UNDERSTAND??

(enter to proceed, ctrl+c to quit)


Would you like to enable rootfs restore? It will add an option to quickly revert all changes and re-enroll. (Y/n)y
----- stage 1: grabbing disk configuration -----
target kern is 2@/dev/mmcblk0p2
target root is 3@/dev/mmcblk0p3

backup kern is 4@/dev/mmcblk0p4
backup root is 5@/dev/mmcblk0p5
----- stage 2: patching target rootfs -----
disabling autoupdates
dropping crossystem.sh
staging sshd
dropping pollen
preventing stateful bootloop
installing mush shell
dropping fakemurk daemon
----- stage 3: cleaning up -----
"echo "----- stage 3: cleaning up -----"" command failed with exit code 6. THIS IS A BUG, REPORT IT HERE https://github.com/MercuryWorkshop/fakemurk
localhost /home/chronos/user #

**Comment by CoolElectronics** [comment]
the output of the commands i gave, not the script

**Comment by MythicalTrashcan** [comment]
How do I send that?

**Comment by CoolElectronics** [comment]
??? the same way you sent the logs?

**Comment by MythicalTrashcan** [comment]
Do you mean the code I used to run this.

**Comment by CoolElectronics** [comment]
the commands i described in #6. run them, then give me the output

**Comment by MythicalTrashcan** [comment]
localhost /home/chronos/user # sudo vpd.old
sudo: vpd.old: command not found
localhost /home/chronos/user # sudo crosssystem.old
sudo: crosssystem.old: command not found
localhost /home/chronos/user #

**Comment by CoolElectronics** [comment]
sorry i spelled crossystem with 3 s do it with 2?

**Comment by MythicalTrashcan** [comment]
same result.

**Comment by CoolElectronics** [comment]
vpd -i RW_VPD -s check_enrollment=1
echo $?
crossystem block_devmode=0
echo $?

**Comment by MythicalTrashcan** [comment]
localhost / # vpd -i RW_VPD -s check_enrollment=1
echo $?
crossystem block_devmode=0
echo $?
0
0
localhost / #

**Comment by MythicalTrashcan** [comment]
Oh

**Comment by MythicalTrashcan** [comment]
My brain just blew up. I am not even enrolled.

**Comment by TheMemeSniper** [comment]
🐟
