### ISSUE TITLE
readonly filesystem and exit code 4

### ISSUE THREAD

**Issue by misterfonka** [MercuryWorkshop/fakemurk#41]
Issue description:

Fakemurk was disabling auto updates, gave an error saying read-only file system and then another error saying I need to report this as a bug.

Terminal output:

----- stage 2: patching target rootfs -----
removing rootfs verification on target kernel /dev/mmcblk0p4
disabling autoupdates
sed: cannot remove /tmp/rootmnt/etc/sedEeRwEy: Read-only file system
"prepare_target_root" command failed with exit code 4. THIS IS A BUG, REPORT IT HERE https://github.com/MercuryWorkshop/fakemurk

Additional notes:

I did run the command "fsck -f $(rootdev)" and rebooted.

**Comment by rainestorme** [comment]
Try recovering and trying again, that usually fixes issues.

**Comment by JimDude7404** [comment]
fsck -f $(rootdev)

run that, as per the instructions.
