### ISSUE TITLE
ERROR: your firmware will only boot signed images 

### ISSUE THREAD

**Issue by rahin22** [MercuryWorkshop/fakemurk#42]
# ISSUE DESCRIPTION

Fakemurk was removing rootfs verification on target kernel /dev/mmcblk1p2, gave the error mentioned in the title and said to report it as a bug

# TERMINAL OUTPUT (if any)

----- stage 2: patching target rootfs -----
removing rootfs verification on target kernel /dev/mmcblk1p2

  ERROR: YOUR FIRMWARE WILL ONLY BOOT SIGNED IMAGES.

  Modifying the kernel or root filesystem will result in an unusable system.  If
  you really want to make this change, allow the firmware to boot self-signed
  images by running:

    sudo crossystem dev_boot_signed_only=0

  before re-executing this command.
  
"echo "----- stage 2: patching target rootfs -----"" command failed with exit code 1. THIS IS A BUG, REPORT IT HERE https://github.com/MercuryWorkshop/fakemurk

# ADDITIONAL NOTES

running the command 
`sudo crossystem dev_boot_signed_only=0`
resolved the issue

**Comment by CoolElectronics** [comment]
cool thanks for making me aware of the edge case

**Comment by BinBashBanana** [comment]
crouton automatically enables this :(
