### ISSUE TITLE
exit code 32

### ISSUE THREAD

**Issue by imbadattechnology** [MercuryWorkshop/fakemurk#43]
I got an error after pressing Y when it gave me disclaimier and it told me its a bug and to report it

# TERMINAL OUTPUT (if any)

# ADDITIONAL NOTES

**Comment by imbadattechnology** [comment]
i got an exit code 1 now

**Comment by CoolElectronics** [comment]
again, you didn't follow the template, so no one will help you.
go through recovery with a usb and run the script again, this time paste in the full script output

**Comment by CoolElectronics** [comment]
you. need. to. give. me. the. full. output.

do you honestly expect me to help you if you don't give me any information at all???
saying "exit code 1" is like saying "something went wrong". i can't do shit with that


paste in the FULL OUTPUT

**Comment by imbadattechnology** [comment]
ok heres thhe output 
installing mush shell
dropping fakemurk daemon
preparing ausystem
stage 3: cleaning up
"echo" --- stage 3: cleaning up command failed with exit code 1. THIS IS A BUG REPORT IT HERE https://github.com/MercuryWorkshop/fakemurk

**Comment by imbadattechnology** [comment]
do you see the output

**Comment by imbadattechnology** [comment]
full script output


Would you like to enable rootfs restore? It will add an option to quickly revert all changes and re-enroll. (Y/n) Y
----- stage 1: grabbing disk configuration -----
target kern is 4@/dev/mmcblk0p4
target root is 5@/dev/mmcblk0p5

backup kern is 2@/dev/mmcblk0p2
backup root is 3@/dev/mmcblk0p3
----- stage 2: patching target rootfs -----
disabling autoupdates
dropping crossystem.sh
staging sshd
dropping pollen
preventing stateful bootloop
installing mush shell
dropping fakemurk daemon
preparing ausystem
----- stage 3: cleaning up -----
"echo "----- stage 3: cleaning up -----"" command failed with exit code 1. THIS IS A BUG, REPORT IT HERE https://github.com/MercuryWorkshop/fakemurk
