### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by imbadattechnology** [MercuryWorkshop/fakemurk#45]
So after recovering and booting into chrome. Do  I need to reinstall legacy bios again or should I just go straight to the terminal and paste the fakemurk commands

im on 107

**Comment by CoolElectronics** [comment]
you don't need it at all unless you're planning on using linux, but yes you would reinstall it

**Comment by imbadattechnology** [comment]
Huh? If im just keeping dev mode do I need to reinstall it?

**Comment by imbadattechnology** [comment]
hellO?
