### ISSUE TITLE
Exit code 2 "No such file or directory issue"

### ISSUE THREAD

**Issue by imbadattechnology** [MercuryWorkshop/fakemurk#46]
Got an exit code 2 about No such file or directory

# TERMINAL OUTPUT 

Would you like to enable rootfs restore? It will add an option to quickly revert all changes and re-enroll. (Y/n)Y
----- stage 1: grabbing disk configuration -----
target kern is 4@/dev/mmcblk0p4
target root is 5@/dev/mmcblk0p5

backup kern is 2@/dev/mmcblk0p2
backup root is 3@/dev/mmcblk0p3
----- stage 2: patching target rootfs -----
removing rootfs verification on target kernel /dev/mmcblk0p4
disabling autoupdates
sed: can't read /tmp/rootmnt/etc/lsb-release: No such file or directory
"prepare_target_root" command failed with exit code 2. THIS IS A BUG, REPORT IT HERE https://github.com/MercuryWorkshop/fakemurk

# ADDITIONAL NOTES

I am on 107 and yes I checked

**Comment by JimDude7404** [comment]
Restore again, that will fix your issue.
