### ISSUE TITLE
How do I install Mush?

### ISSUE THREAD

**Issue by JackWagon885** [MercuryWorkshop/fakemurk#49]
- [Y] I am not reporting an issue unrelated to the fakemurk utilities.
- [?] I am not reporting an issue related to a borked system.
- [Y] I am not an angry sysadmin.
- [N] I have attached the complete and full output from the terminal

# ISSUE DESCRIPTION
There are no instructions & it is unclear how to install Mush. Can you please update the README.md to include instructions on how to install Mush?

# TERMINAL OUTPUT (if any)

# ADDITIONAL NOTES

**Comment by TheMemeSniper** [comment]
mush is automatically installed when fakemurk is installed

**Comment by JackWagon885** [comment]
thanks
