### ISSUE TITLE
patching target to rootfs - "command failed with exit code 32"

### ISSUE THREAD

**Issue by Anonymadly** [MercuryWorkshop/fakemurk#5]
- [x] I am not reporting an issue unrelated to the fakemurk utilities.
- [x] I am not reporting an issue related to a borked system.
- [x] I am not an angry sysadmin.
- [x] I have attached the complete and full output from the terminal

# ISSUE DESCRIPTION
Running fakemurk using 
```
crosh> shell
chronos@localhost / $ sudo su
localhost / # bash <(curl -SLk https://github.com/MercuryWorkshop/fakemurk/releases/latest/download/fakemurk.sh)
```
The following appears:

# TERMINAL OUTPUT (if any)
```
Would you like to enable rootfs restore? It will add an option to quickly revert all changes and re-enroll. (Y/n)Y
----- stage 1: grabbing disk configuration -----
target kern is 2@/dev/mmcblk0p2
target root is 3@/dev/mmcblk0p3

backup kern is 4@/dev/mmcblk0p4
backup root is 5@/dev/mmcblk0p5
----- stage 2: patching target rootfs -----
removing rootfs verification on target kernel /dev/mmcblk0p2
mount: /tmp/rootmnt: /dev/mmcblk0p3 already mounted or mount point busy.
"echo "----- stage 2: patching target rootfs -----"" command failed with exit code 32. THIS IS A BUG, REPORT IT HERE https://github.com/MercuryWorkshop/fakemurk
```
I'm not too familiar with ChromeOS, so I'm not sure why this is happening. 

# ADDITIONAL NOTES
- This is on ChromeOS Version `107.0.5304.110`
- Platform is `octopus`

**Comment by CoolElectronics** [comment]
very odd
what seems to have happened here is there's a pending update waiting to be applied, and that's messing up what it thinks the target should be
in your case, a reboot should fix this? if not a recovery definitely will

no idea how to detect this, i guess i could just see whether or not it fails and go based on that

**Comment by Anonymadly** [comment]
Yep, that's correct! I rebooted and the error has not come back since.

Just a note for the reboot:
It actually updated me to `111`, however, after downgrading to `107` again, using sh1mmer to re-unenroll, and then finally running fakemurk a second time, it worked flawlessly.
