### ISSUE TITLE
exit code 6.

### ISSUE THREAD

**Issue by scatcat5isdead** [MercuryWorkshop/fakemurk#6]
- [y] I am not reporting an issue unrelated to the fakemurk utilities.
- [y] I am not reporting an issue related to a borked system.
- []y I am not an angry sysadmin.
- [y] I have attached the complete and full output from the terminal

# ISSUE DESCRIPTION 

# TERMINAL OUTPUT  crosh> shell
chronos@localhost / $ sudo su

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

localhost / # bash <(curl -SLk https://github.com/MercuryWorkshop/fakemurk/releases/latest/download/fakemurk.sh)

 ________ ________  ___  __    _______   _____ ______   ___  ___  ________  ___  __
|\  _____\\   __  \|\  \|\  \ |\  ___ \ |\   _ \  _   \|\  \|\  \|\   __  \|\  \|\  \
\ \  \__/\ \  \|\  \ \  \/  /|\ \   __/|\ \  \\\__\ \  \ \  \\\  \ \  \|\  \ \  \/  /|_
 \ \   __\\ \   __  \ \   ___  \ \  \_|/_\ \  \\|__| \  \ \  \\\  \ \   _  _\ \   ___  \
  \ \  \_| \ \  \ \  \ \  \\ \  \ \  \_|\ \ \  \    \ \  \ \  \\\  \ \  \\  \\ \  \\ \  \
   \ \__\   \ \__\ \__\ \__\\ \__\ \_______\ \__\    \ \__\ \_______\ \__\\ _\\ \__\\ \__\
    \|__|    \|__|\|__|\|__| \|__|\|_______|\|__|     \|__|\|_______|\|__|\|__|\|__| \|__|

THIS IS FREE SOFTWARE! if you paid for this, you have been scammed and should demand your money back

fakemurk - a tool made by Mercury Workshop to spoof verified boot while enrolled
you can find this script, its explanation, and documentation here: https://github.com/MercuryWorkshop/fakemurk

WARNING: THIS SCRIPT WILL REQUIRE THE REMOVAL OF ROOTFS VERIFICATION, AND THE DISABLING OF AUTOUPDATES
THIS MEANS THAT IF YOU EVER TURN OFF DEVMODE, YOUR SYSTEM WILL BE BRICKED UNTIL RECOVERY

WE ARE NOT RESPONSIBLE FOR DAMAGE, YOU BEING STUPID AND MISUSING THIS, OR GETTING IN TROUBLE
DO YOU UNDERSTAND??

(enter to proceed, ctrl+c to quit)

Would you like to enable rootfs restore? It will add an option to quickly revert all changes and re-enroll. (Y/n)y
----- stage 1: grabbing disk configuration -----
target kern is 4@/dev/mmcblk0p4
target root is 5@/dev/mmcblk0p5

backup kern is 2@/dev/mmcblk0p2
backup root is 3@/dev/mmcblk0p3
----- stage 2: patching target rootfs -----
removing rootfs verification on target kernel /dev/mmcblk0p4
disabling autoupdates
dropping crossystem.sh
staging sshd
dropping pollen
preventing stateful bootloop
installing mush shell
dropping fakemurk daemon
----- stage 3: cleaning up -----
"echo "----- stage 3: cleaning up -----"" command failed with exit code 6. THIS IS A BUG, REPORT IT HERE https://github.com/MercuryWorkshop/fakemurk
# ADDITIONAL NOTES

**Comment by CoolElectronics** [comment]
assuming you haven't rebooted yet (which if you do you probably need to recover)

try going into the terminal again and typing `sudo vpd.old`, paste in the result
then type in `sudo crosssytem.old`, paste in the result

very likely that using a recovery image and trying again will fix

**Comment by CoolElectronics** [comment]
stale
