### ISSUE TITLE
exit code 1

### ISSUE THREAD

**Issue by AlphaKelo** [MercuryWorkshop/fakemurk#8]
- [] I am not reporting an issue unrelated to the fakemurk utilities.
- [] I am not reporting an issue related to a borked system.
- [] I am not an angry sysadmin.
- [] I have attached the complete and full output from the terminal

# ISSUE DESCRIPTION
I've run fakemurk multiple times on v107, but to no avail

# TERMINAL OUTPUT (if any)
Welcome to crosh, the ChromeOS developer shell.

If you got here by mistake, don't panic!  Just close this tab and carry on.

Type 'help' for a list of commands.

If you want to customize the look/behavior, you can use the options page.
Load it by using the Ctrl-Shift-P keyboard shortcut.

crosh> shell
chronos@localhost / $ sudo su                  
localhost / # bash <(curl -SLk https://github.com/MercuryWorkshop/fakemurk/releases/latest/download/fakemurk.sh)

 ________ ________  ___  __    _______   _____ ______   ___  ___  ________  ___  __
|\  _____\\   __  \|\  \|\  \ |\  ___ \ |\   _ \  _   \|\  \|\  \|\   __  \|\  \|\  \
\ \  \__/\ \  \|\  \ \  \/  /|\ \   __/|\ \  \\\__\ \  \ \  \\\  \ \  \|\  \ \  \/  /|_
 \ \   __\\ \   __  \ \   ___  \ \  \_|/_\ \  \\|__| \  \ \  \\\  \ \   _  _\ \   ___  \
  \ \  \_| \ \  \ \  \ \  \\ \  \ \  \_|\ \ \  \    \ \  \ \  \\\  \ \  \\  \\ \  \\ \  \
   \ \__\   \ \__\ \__\ \__\\ \__\ \_______\ \__\    \ \__\ \_______\ \__\\ _\\ \__\\ \__\
    \|__|    \|__|\|__|\|__| \|__|\|_______|\|__|     \|__|\|_______|\|__|\|__|\|__| \|__|

THIS IS FREE SOFTWARE! if you paid for this, you have been scammed and should demand your money back

fakemurk - a tool made by Mercury Workshop to spoof verified boot while enrolled
you can find this script, its explanation, and documentation here: https://github.com/MercuryWorkshop/fakemurk

WARNING: THIS SCRIPT WILL REQUIRE THE REMOVAL OF ROOTFS VERIFICATION, AND THE DISABLING OF AUTOUPDATES
THIS MEANS THAT IF YOU EVER TURN OFF DEVMODE, YOUR SYSTEM WILL BE BRICKED UNTIL RECOVERY

WE ARE NOT RESPONSIBLE FOR DAMAGE, YOU BEING STUPID AND MISUSING THIS, OR GETTING IN TROUBLE
DO YOU UNDERSTAND??

(enter to proceed, ctrl+c to quit)

Would you like to enable rootfs restore? It will add an option to quickly revert all changes and re-enroll. (Y/n)y
----- stage 1: grabbing disk configuration -----
target kern is 4@/dev/mmcblk0p4
target root is 5@/dev/mmcblk0p5

backup kern is 2@/dev/mmcblk0p2
backup root is 3@/dev/mmcblk0p3
----- stage 2: patching target rootfs -----
mkdir: cannot create directory '/tmp/rootmnt': File exists
"echo "----- stage 2: patching target rootfs -----"" command failed with exit code 1. THIS IS A BUG, REPORT IT HERE https://github.com/MercuryWorkshop/fakemurk

# ADDITIONAL NOTES
I'm on an unenrolled chromebook, and I've installed MrChromebox's RW_LEGACY bios.

**Comment by dabeast402** [comment]
same here but I got to stage 3 cleaning up

**Comment by dabeast402** [comment]
you can find this script, its explanation, and documentation here: https://github.com/MercuryWorkshop/fakemurk

WARNING: THIS SCRIPT WILL REQUIRE THE REMOVAL OF ROOTFS VERIFICATION, AND THE DISABLING OF AUTOUPDATES
THIS MEANS THAT IF YOU EVER TURN OFF DEVMODE, YOUR SYSTEM WILL BE BRICKED UNTIL RECOVERY

WE ARE NOT RESPONSIBLE FOR DAMAGE, YOU BEING STUPID AND MISUSING THIS, OR GETTING IN TROUBLE
DO YOU UNDERSTAND??

(enter to proceed, ctrl+c to quit)


Would you like to enable rootfs restore? It will add an option to quickly revert all changes and re-enroll. (Y/n)Y
----- stage 1: grabbing disk configuration -----
target kern is 4@/dev/mmcblk0p4
target root is 5@/dev/mmcblk0p5

backup kern is 2@/dev/mmcblk0p2
backup root is 3@/dev/mmcblk0p3
----- stage 2: patching target rootfs -----
disabling autoupdates
dropping crossystem.sh
/tmp/rootmnt/usr/bin/crossystem.old: line 24: =: command not found
staging sshd
dropping pollen
preventing stateful bootloop
installing mush shell
dropping fakemurk daemon
----- stage 3: cleaning up -----
"echo "----- stage 3: cleaning up -----"" command failed with exit code 1. THIS IS A BUG, REPORT IT HERE https://github.com/MercuryWorkshop/fakemurk
localhost / # bash <(curl -SLk https://github.com/MercuryWorkshop/fakemurk/releases/latest/download/fakemurk.sh)

**Comment by CoolElectronics** [comment]
both cases are user error, failing to recover before running the script again
